### ISSUE TITLE
public display

### ISSUE THREAD

**Issue by ZHangZHengEric** [SJTU-LIT/ceval#54]
I submitted our model’s results for public display, and how long will it take to process them? Thank you.​​​​​​

**Comment by zzh068** [comment]
Thanks for your affirmation and recognition of C-Eval~
Because there some model may update their records multiple times within a few days, we update the leaderboard every 2-3 days. If there is an urgent need to make the results public, you can contact us via email or create an issuse. 
In general, we conduct preliminary review and screening of the submitted records that need to be made public, and we may reach out to some submitters for further confirmation before making them public.

**Comment by ZHangZHengEric** [comment]
Thank you for your response, and also thank you for your work on model evaluation.
